### ISSUE TITLE
Does it works with PostgreSQL

### ISSUE THREAD

**Issue by GabrielBlondeau-Kirby** [erikvw/django-crypto-fields#12]
Hi,

> Python 3.8, 3.9, 3.10, Django 3.2, 4.0, 4.1 using mysql

Is it also working with other SQL system like PostgreSQL ?

Btw, great work !

**Comment by erikvw** [comment]
next release will support PostgreSQL.

**Comment by erikvw** [comment]
0.4.2: add support for PostgreSQL
