### ISSUE TITLE
 OSError: mysql_config not found

### ISSUE THREAD

**Issue by MichaelPavlov** [erikvw/django-crypto-fields#5]
Hello! I'm trying to install the extensions's requirements, but it fails with error `OSError: mysql_config not found`. I'm using postgres, is this extension only for mysql db?

**Comment by erikvw** [comment]
Hi. So far only the module only supports mysql. As I recall the main issue was with the BinaryField in the Crypt model.  But I am hoping to find some time to resolve this.

**Comment by erikvw** [comment]
see #3
